# frozen_string_literal: true

COMPARATOR_MODELS = [
  { id: "linreg", name: "Régression Linéaire", icon: "📈", type: "Régression",
    scaling: true, outliers_sensitive: true, interpretable: true,
    handles_nonlinear: false, needs_feature_eng: true,
    speed_train: "⚡ Instant", speed_predict: "⚡ Instant",
    n_params: "~N features", overfitting_risk: "Faible",
    handles_missing: false, handles_categorical: false,
    when: "Baseline régression, relations linéaires, besoin d'interpréter les coefficients.",
    sklearn: "LinearRegression(), Ridge(), Lasso()" },

  { id: "logreg", name: "Régression Logistique", icon: "🎯", type: "Classification",
    scaling: true, outliers_sensitive: true, interpretable: true,
    handles_nonlinear: false, needs_feature_eng: true,
    speed_train: "⚡ Instant", speed_predict: "⚡ Instant",
    n_params: "~N features", overfitting_risk: "Faible",
    handles_missing: false, handles_categorical: false,
    when: "Baseline classification, probabilités calibrées, besoin d'interpréter.",
    sklearn: "LogisticRegression()" },

  { id: "tree", name: "Arbre de Décision", icon: "🌳", type: "Les deux",
    scaling: false, outliers_sensitive: false, interpretable: true,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "⚡ Rapide", speed_predict: "⚡ Instant",
    n_params: "Variable (profondeur)", overfitting_risk: "Élevé",
    handles_missing: false, handles_categorical: false,
    when: "Besoin d'expliquer les décisions (médical, finance), données non-linéaires simples.",
    sklearn: "DecisionTreeClassifier(), DecisionTreeRegressor()" },

  { id: "rf", name: "Random Forest", icon: "🌲", type: "Les deux",
    scaling: false, outliers_sensitive: false, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔶 Moyen", speed_predict: "⚡ Rapide",
    n_params: "N arbres × profondeur", overfitting_risk: "Moyen",
    handles_missing: false, handles_categorical: false,
    when: "Bon par défaut, robuste, feature importances. Premier choix avant XGBoost.",
    sklearn: "RandomForestClassifier(), RandomForestRegressor()" },

  { id: "xgb", name: "XGBoost", icon: "🚀", type: "Les deux",
    scaling: false, outliers_sensitive: false, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔶 Moyen", speed_predict: "⚡ Rapide",
    n_params: "N arbres × profondeur", overfitting_risk: "Moyen-Élevé",
    handles_missing: true, handles_categorical: false,
    when: "Performance maximale sur données tabulaires. Kaggle winner. Nécessite du tuning.",
    sklearn: "XGBClassifier(), XGBRegressor()" },

  { id: "knn", name: "KNN", icon: "🔵", type: "Les deux",
    scaling: true, outliers_sensitive: true, interpretable: true,
    handles_nonlinear: true, needs_feature_eng: true,
    speed_train: "⚡ Instant (stocke)", speed_predict: "🔴 Lent (calcule tout)",
    n_params: "0 (lazy)", overfitting_risk: "Moyen",
    handles_missing: false, handles_categorical: false,
    when: "Petits datasets, systèmes de recommandation simples, baseline non-linéaire.",
    sklearn: "KNeighborsClassifier(), KNeighborsRegressor()" },

  { id: "svm", name: "SVM", icon: "⬛", type: "Classification",
    scaling: true, outliers_sensitive: false, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔴 Lent (> 10K lignes)", speed_predict: "🔶 Moyen",
    n_params: "Support vectors", overfitting_risk: "Faible-Moyen",
    handles_missing: false, handles_categorical: false,
    when: "Petits datasets haute dimension, frontières complexes. Kernel RBF puissant.",
    sklearn: "SVC(), SVR()" },

  { id: "kmeans", name: "K-Means", icon: "🧩", type: "Non-supervisé",
    scaling: true, outliers_sensitive: true, interpretable: true,
    handles_nonlinear: false, needs_feature_eng: true,
    speed_train: "⚡ Rapide", speed_predict: "⚡ Instant",
    n_params: "K × N features", overfitting_risk: "N/A",
    handles_missing: false, handles_categorical: false,
    when: "Segmentation clients, groupes naturels, réduction de complexité.",
    sklearn: "KMeans(n_clusters=K)" },

  { id: "nn", name: "Neural Network (Dense)", icon: "🧠", type: "Les deux",
    scaling: true, outliers_sensitive: true, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔴 Lent (GPU)", speed_predict: "🔶 Moyen",
    n_params: "Centaines à millions", overfitting_risk: "Élevé",
    handles_missing: false, handles_categorical: false,
    when: "Gros datasets, problèmes complexes, quand les méthodes classiques plafonnent.",
    sklearn: "Keras Sequential() + Dense()" },

  { id: "cnn", name: "CNN", icon: "🖼️", type: "Classification images",
    scaling: true, outliers_sensitive: false, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔴 Lent (GPU)", speed_predict: "🔶 Moyen",
    n_params: "Millions (VGG16: 138M)", overfitting_risk: "Élevé",
    handles_missing: false, handles_categorical: false,
    when: "Classification d'images, détection d'objets. Transfer Learning avec VGG16/ResNet.",
    sklearn: "Keras Conv2D() + MaxPooling2D()" },

  { id: "rnn", name: "RNN / LSTM", icon: "📝", type: "Séquences / Texte",
    scaling: true, outliers_sensitive: false, interpretable: false,
    handles_nonlinear: true, needs_feature_eng: false,
    speed_train: "🔴 Lent (GPU)", speed_predict: "🔶 Moyen",
    n_params: "Millions", overfitting_risk: "Élevé",
    handles_missing: false, handles_categorical: false,
    when: "Séries temporelles, NLP, traduction, génération de texte.",
    sklearn: "Keras LSTM() + Embedding()" },
]
