# frozen_string_literal: true

MODEL_CONCEPTS = [
  { model: "Régression Linéaire",
    icon: "📈",
    color: "blue",
    params_name: "Coefficients (poids + biais)",
    params_example: "prix = <strong>2847</strong> × surface + <strong>15200</strong> × nb_pièces − <strong>8400</strong>",
    params_count: "1 par feature + 1 intercept",
    what_fit_does: "Minimise la somme des erreurs² (moindres carrés) pour trouver les meilleurs coefficients.",
    what_predict_does: "Multiplie chaque feature par son coefficient, additionne, renvoie le résultat.",
    saved_model: "Un vecteur de N+1 nombres (coefficients + intercept).",
    code_inspect: "model.coef_, model.intercept_" },

  { model: "Régression Logistique",
    icon: "🎯",
    color: "green",
    params_name: "Coefficients + sigmoïde",
    params_example: "P(spam) = σ(<strong>0.8</strong> × nb_liens + <strong>1.2</strong> × mots_suspects − <strong>3.1</strong>)",
    params_count: "1 par feature + 1 intercept",
    what_fit_does: "Maximise la vraisemblance (log-loss) pour séparer les classes.",
    what_predict_does: "Calcule la somme pondérée, passe dans la sigmoïde σ(x) = 1/(1+e⁻ˣ), renvoie une probabilité.",
    saved_model: "Les mêmes coefficients qu'une régression linéaire. La sigmoïde est juste une transformation appliquée dessus.",
    code_inspect: "model.coef_, model.intercept_" },

  { model: "Arbre de Décision",
    icon: "🌳",
    color: "green",
    params_name: "Seuils de split + valeurs aux feuilles",
    params_example: "SI surface > <strong>80</strong> ET ville = <strong>Paris</strong> → <strong>350 000€</strong>",
    params_count: "2 par nœud (feature + seuil) + 1 par feuille",
    what_fit_does: "Teste tous les splits possibles, choisit celui qui réduit le plus l'impureté (Gini ou entropie).",
    what_predict_does: "Descend l'arbre en suivant les règles, renvoie la valeur/classe de la feuille atteinte.",
    saved_model: "Une structure d'arbre : chaque nœud stocke (quelle feature, quel seuil, enfant gauche, enfant droit).",
    code_inspect: "model.tree_.feature, model.tree_.threshold" },

  { model: "Random Forest",
    icon: "🌲",
    color: "green",
    params_name: "N arbres indépendants",
    params_example: "<strong>100 arbres</strong>, chacun entraîné sur un sous-échantillon aléatoire, qui votent ensemble",
    params_count: "100 × (paramètres d'un arbre) = des milliers de seuils",
    what_fit_does: "Entraîne N arbres en parallèle sur des échantillons bootstrap (bagging). Chaque arbre ne voit qu'un sous-ensemble de features.",
    what_predict_does: "Fait prédire chaque arbre, puis vote majoritaire (classif) ou moyenne (régression).",
    saved_model: "Une liste de N arbres. Plus N est grand, plus le fichier est lourd.",
    code_inspect: "model.estimators_, model.feature_importances_" },

  { model: "XGBoost / Gradient Boosting",
    icon: "🚀",
    color: "yellow",
    params_name: "N arbres séquentiels + learning rate",
    params_example: "Arbre 1 prédit 200K, erreur = +50K → Arbre 2 corrige de <strong>−50K × 0.1</strong> = −5K → ...",
    params_count: "N arbres × paramètres par arbre + hyperparamètres (lr, max_depth...)",
    what_fit_does: "Entraîne les arbres un par un. Chaque nouvel arbre apprend à corriger les résidus (erreurs) du précédent.",
    what_predict_does: "Somme les prédictions de tous les arbres, pondérées par le learning rate.",
    saved_model: "Une séquence ordonnée d'arbres. L'ordre compte (contrairement au Random Forest).",
    code_inspect: "model.feature_importances_, model.get_booster()" },

  { model: "KNN (K-Nearest Neighbors)",
    icon: "🔵",
    color: "cyan",
    params_name: "Aucun paramètre appris !",
    params_example: "Le 'modèle' = <strong>le dataset d'entraînement entier</strong>, stocké en mémoire",
    params_count: "0 paramètres. Le dataset EST le modèle.",
    what_fit_does: "Stocke les données en mémoire. C'est tout. (d'où le nom 'lazy learner')",
    what_predict_does: "Calcule la distance avec TOUS les points d'entraînement, prend les K plus proches, vote.",
    saved_model: "Le dataset complet. Un KNN sur 1M de lignes = un fichier de 1M de lignes.",
    code_inspect: "model._fit_X (les données stockées)" },

  { model: "SVM (Support Vector Machine)",
    icon: "⬛",
    color: "purple",
    params_name: "Vecteurs supports + poids",
    params_example: "Trouve la frontière qui <strong>maximise la marge</strong> entre les classes. Ne retient que les points proches de la frontière.",
    params_count: "Un sous-ensemble des données (les support vectors) + leurs poids",
    what_fit_does: "Cherche l'hyperplan qui sépare les classes avec la plus grande marge. Avec un kernel RBF, projette d'abord dans un espace de dimension supérieure.",
    what_predict_does: "Calcule de quel côté de la frontière tombe le nouveau point.",
    saved_model: "Les vecteurs supports (quelques % du dataset) + les coefficients duaux.",
    code_inspect: "model.support_vectors_, model.dual_coef_" },

  { model: "K-Means",
    icon: "🧩",
    color: "purple",
    params_name: "Coordonnées des centroïdes",
    params_example: "Cluster 0 : centroïde à (<strong>25 ans, 35K€, Paris</strong>), Cluster 1 : (<strong>45 ans, 72K€, Lyon</strong>)",
    params_count: "K × nombre de features",
    what_fit_does: "Place K centroïdes aléatoirement, puis alterne : (1) assigne chaque point au centroïde le plus proche, (2) recalcule les centroïdes. Répète jusqu'à convergence.",
    what_predict_does: "Calcule la distance avec chaque centroïde, renvoie le numéro du plus proche.",
    saved_model: "K vecteurs de dimension N (les centroïdes). Pour K=5 et 10 features : 50 nombres.",
    code_inspect: "model.cluster_centers_, model.labels_" },

  { model: "PCA",
    icon: "🧮",
    color: "purple",
    params_name: "Axes de projection (composantes principales)",
    params_example: "PC1 = <strong>0.7</strong> × surface + <strong>0.5</strong> × prix − <strong>0.1</strong> × étage (l'axe qui capte le plus de variance)",
    params_count: "n_components × n_features (une matrice de rotation)",
    what_fit_does: "Calcule les directions de variance maximale dans les données (vecteurs propres de la matrice de covariance).",
    what_predict_does: "Projette les données sur ces axes (transform, pas predict).",
    saved_model: "La matrice de composantes + la moyenne de chaque feature (pour centrer).",
    code_inspect: "pca.components_, pca.explained_variance_ratio_" },

  { model: "Réseau de Neurones (Dense)",
    icon: "🧠",
    color: "red",
    params_name: "Matrices de poids + vecteurs de biais",
    params_example: "Couche Dense(64) avec 10 inputs : matrice <strong>10×64</strong> = 640 poids + <strong>64</strong> biais = <strong>704 paramètres</strong>",
    params_count: "Peut aller de quelques centaines à des milliards (GPT-4 ≈ 1 700 milliards)",
    what_fit_does: "Propagation avant → calcul de la loss → rétropropagation du gradient → mise à jour des poids (gradient descent). Répété sur chaque batch, chaque epoch.",
    what_predict_does: "Propagation avant uniquement : multiplie les inputs par les poids, ajoute les biais, applique l'activation, couche par couche.",
    saved_model: "Toutes les matrices de poids de chaque couche. Un réseau simple ≈ quelques Ko. VGG16 ≈ 528 Mo.",
    code_inspect: "model.get_weights(), model.summary()" },
]
